- name: Create LXCs
  community.general.terraform:
    state: present
    project_path: ~/repos/homelab/tf/adguard
    complex_vars: true
    force_init: true
    variables:
      pve_api_host: "https://pmx.{{ secret_base_domain }}/api2/json"
      lxc_password: "{{ secret_lxc_password }}"
      pve_nodes: "{{ groups['proxmox'] }}"
      lxc_ips: ["172.16.0.13/24", "172.16.0.14/24", "172.16.0.15/24", "172.16.0.16/24"]
      lxc_hostnames: ["ag1", "ag2", "ag3", "agsync"]
      lxc_gw: "{{ secret_resolver_router }}"
      lxc_template: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
