- name: Copy DNS Cert from pfsense
  ansible.builtin.command:
    cmd: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ secret_resolver_router }}:/cf/conf/acme/omada.{{ secret_base_domain }}.* /container-vols/certs" # noqa yaml[line-length]
    creates: /certs/omada.{{ secret_base_domain }}.fullchain

- name: Copy Docker-Compose
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /container-vols/omada/
    mode: "0770"

- name: Deploy Omada
  community.docker.docker_compose_v2:
    project_src: /container-vols/omada/
    state: present
    project_name: omada
