- name: Create Config Directory
  ansible.builtin.file:
    path: /container-vols/omada/
    state: directory
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy Docker-Compose
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /container-vols/omada/
    mode: "0770"

- name: Deploy Omada
  community.docker.docker_compose_v2:
    project_src: /container-vols/omada/
    state: present
    project_name: omada
