###
# @name getBearerToken

POST {{ portainer_host }}/api/auth
Content-Type: application/json
{
    "username": "{{ portainer_user }}",
    "password": "{{ portainer_pass }}"
}

###
# @name getConfig
# @ref getBearerToken

GET {{ portainer_host }}/api/settings
Authorization: Bearer {{ getBearerToken.jwt }}

###
# @name generateKey
# @ref getBearerToken

POST {{ portainer_host }}/api/endpoints/edge/generate-key
Authorization: Bearer {{ getBearerToken.jwt }}


###
# @name approveHost
# @ref getBearerToken
POST {{ portainer_host }}/api/endpoints/903/edge/trust
Authorization: Bearer {{ getBearerToken.jwt }}


###
# @name getEndpoints
# @ref getBearerToken

GET {{ portainer_host }}/api/endpoints
Authorization: Bearer {{ getBearerToken.jwt }}

###/
# @name createEndpoint
# @ref getBearerToken

POST {{ portainer_host }}/api/endpoints
Authorization: Bearer {{ getBearerToken.jwt }}
Content-Type: application/x-www-form-urlencoded
Name=amy&EndpointCreationType=4&GroupID=2

###
# @name getRegistries
# @ref getBearerToken

GET {{ portainer_host }}/api/registries
Authorization: Bearer {{ getBearerToken.jwt }}

###
# @name getGHCreds
# @ref getBearerToken

GET {{ portainer_host }}/api/users/1/gitcredentials
Authorization: Bearer {{ getBearerToken.jwt }}


###
# @name deleteGHCreds
# @ref getBearerToken

DELETE {{ portainer_host }}/api/users/1/gitcredentials/1
Authorization: Bearer {{ getBearerToken.jwt }}

###
# @name deleteDHCreds
# @ref getBearerToken

DELETE {{ portainer_host }}/api/registries/2
Authorization: Bearer {{ getBearerToken.jwt }}


###
# @name getEdgeStacks
# @ref getBearerToken

GET {{ portainer_host }}/api/edge_stacks
Authorization: Bearer {{ getBearerToken.jwt }}
