- name: Install KeepaliveD
  become: true
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Create Certs Directory
  ansible.builtin.file:
    path: /container-vols/adguard/certs
    state: directory
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy Config
  ansible.builtin.copy:
    src: "{{ config_source }}/adguard/AdGuardHome.yaml"
    dest: /container-vols/adguard/config
    mode: "0770"
    force: false

- name: Copy Adguard Docker-Compose
  ansible.builtin.copy:
    src: adguard.yml
    dest: /container-vols/adguard/docker-compose.yml
    mode: "0770"

- name: Deploy Adguard
  community.docker.docker_compose_v2:
    project_src: /container-vols/adguard/
    state: present
    project_name: adguard

- name: Copy KeepaliveD DNS Check Script
  ansible.builtin.copy:
    src: healthcheck-dns.sh
    dest: /container-vols/adguard/healthcheck-dns.sh
    mode: "0770"

- name: Copy KeepaliveD HTTPS Check Script
  ansible.builtin.copy:
    src: healthcheck-https.sh
    dest: /container-vols/adguard/healthcheck-https.sh
    mode: "0770"

- name: Configure KeepaliveD
  become: true
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: 'Restart KeepaliveD'
