- name: Download Install Script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh"
    dest: /tmp/install.sh
    mode: "0755"

- name: Install AdGuard
  ansible.builtin.command:
    cmd: "sh /tmp/install.sh -v"
    creates: /opt/AdGuardHome/AdGuardHome

- name: Copy Config
  ansible.builtin.copy:
    src: "{{ config_source }}/adguard/AdGuardHome.yaml"
    dest: /opt/AdGuardHome/AdGuardHome.yaml
    mode: "0770"
    force: false
  notify: "Restart AdGuardHome"
