- name: Install KeepaliveD
  become: true
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Create KeepaliveD Folder
  ansible.builtin.file:
    path: /keepalived
    state: directory
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy KeepaliveD DNS Check Script
  ansible.builtin.copy:
    src: healthcheck-dns.sh
    dest: /keepalived/healthcheck-dns.sh
    mode: "0755"

- name: Copy KeepaliveD HTTPS Check Script
  ansible.builtin.copy:
    src: healthcheck-https.sh
    dest: /keepalived/healthcheck-https.sh
    mode: "0755"

- name: Configure KeepaliveD
  become: true
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: 'Restart KeepaliveD'

- name: Start KeepaliveD
  become: true
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
