- name: Set Resolver to Router
  ansible.builtin.include_tasks: resolver.yml
  vars:
    resolver_ip: "{{ secret_resolver_router }}"

- name: Install KeepaliveD
  ansible.builtin.include_tasks: keepalived.yml

- name: Install Adguard
  ansible.builtin.include_tasks: adguard.yml

- name: Set Resolver Adguard
  ansible.builtin.include_tasks: resolver.yml
  vars:
    resolver_ip: "{{ secret_resolver_adguard }}"

- name: Install Adguard Sync
  ansible.builtin.include_tasks: adguard-sync.yml
  loop: "{{ hostvars[inventory_hostname]['container_vols'] }}"
  when: item == 'adguard-sync'
