- name: Create Adguard
  ansible.builtin.include_tasks: adguard.yml

- name: Create Adguard Sync
  ansible.builtin.include_tasks: adguard-sync.yml
  loop: "{{ hostvars[inventory_hostname]['container_vols'] }}"
  when: item == 'adguard-sync'
