- name: Get Edge Group ID
  ansible.builtin.set_fact:
    eg_id: "{{ edge_groups_existing.json | json_query(query) }}"
  vars:
    query: "[?Name=='{{ group }}'].Id"

- name: Add Agent to Edge Group
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/endpoint_groups/{{ eg_id[0] }}/endpoints/{{ agent_id }}"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "PUT"
    status_code: 204
