- name: Get Admin JWT Token
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/auth"
    method: POST
    body_format: json
    body:
      username: "{{ secret_portainer_admin_user }}"
      password: "{{ secret_portainer_admin_pass }}"
  register: portainer_auth_token

- name: Get Auto Enroll Token
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/endpoints/edge/generate-key"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "POST"
  register: auto_enroll_token

- name: Create Data Folder
  become: true
  ansible.builtin.file:
    path: "/container-vols/portainer-agent"
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Copy Compose File
  become: true
  ansible.builtin.template:
    src: agent.j2
    dest: /container-vols/portainer-agent/docker-compose.yml
    mode: "0664"

- name: Deploy Agent Stack
  become: true
  community.docker.docker_compose_v2:
    project_src: /container-vols/portainer-agent/
    state: present
