- name: Install Docker
  become: true
  block:
    - name: Add Docker apt repository key.
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    - name: Add Docker Repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   bookworm stable
        state: present
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-jsondiff
        update_cache: true
    - name: Add Docker Group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Create container-vols directory
      ansible.builtin.file:
        path: /container-vols
        state: directory
        mode: "0770"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
