- name: Get Admin JWT Token
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/auth"
    method: POST
    body_format: json
    body:
      username: "{{ secret_portainer_admin_user }}"
      password: "{{ secret_portainer_admin_pass }}"
  register: portainer_auth_token

- name: Get Object IDs
  ansible.builtin.include_tasks: get-object-ids.yml

- name: Create/Update Edge Groups
  ansible.builtin.include_tasks: create-update-edge-group.yml
  loop: "{{ portainer_edge_groups }}"
  loop_control:
    label: "{{ group['name'] }}"
    loop_var: group

- name: Refresh Existing Objects
  ansible.builtin.include_tasks: get-object-ids.yml

- name: Create/Update Edge Stacks
  ansible.builtin.include_tasks: create-update-edge-stack.yml
  loop_control:
    loop_var: stack
  loop: "{{ portainer_edge_stacks }}"
