- name: Copy Container Backup Script
  ansible.builtin.copy:
    src: backup-vols.sh
    dest: /container-vols/backup/backup-vols.sh
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Backup Vols service
  become: true
  ansible.builtin.template:
    src: backup-vols.service.j2
    dest: /etc/systemd/system/backup-vols.service
    mode: "0644"

- name: Backup Vols timer
  become: true
  ansible.builtin.copy:
    src: backup-vols.timer
    dest: /etc/systemd/system/backup-vols.timer
    mode: "0644"

- name: Enable Vols timer
  become: true
  ansible.builtin.systemd_service:
    name: backup-vols.timer
    enabled: true
    daemon_reload: true
    state: started