- name: Install Rclone
  become: true
  ansible.builtin.apt:
    name:
      - rclone
    update_cache: true
    state: present

- name: Create Config Directory
  ansible.builtin.file:
    path: /backup
    state: directory
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy GoogleDrive Creds
  ansible.builtin.copy:
    src: "{{ config_source }}/gdrive.json"
    dest: /backup/gdrive.json
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy Rclone Config
  ansible.builtin.copy:
    src: "{{ config_source }}/rclone.conf"
    dest: /backup/rclone.conf
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Backup Adguard
  ansible.builtin.include_tasks: backup-adguard.yml
  loop: "{{ hostvars[inventory_hostname]['backup_adguard'] }}"

- name: Backup Omada
  ansible.builtin.include_tasks: backup-omada.yml
  loop: "{{ hostvars[inventory_hostname]['backup_omada'] }}"

- name: Backup pfsense
  ansible.builtin.include_tasks: backup-pfsense.yml
  loop: "{{ hostvars[inventory_hostname]['backup_pfsense'] }}"
