- name: Install Tailscale
  become: true
  block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'
        force: yes

    - name: Download Tailscale repo list file
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'
        force: yes

    - name: Install Tailscale
      ansible.builtin.apt:
        name:
          - tailscale
        update_cache: true
      notify: "Remove Tailscale Device"

    - name: Start Tailscale
      ansible.builtin.service:
        name: tailscaled
        enabled: true
        state: started
