- name: Install Power Panel
  become: true
  block:
    - name: Download PowerPanel
      ansible.builtin.get_url:
        url: "https://dl4jz3rbrsfum.cloudfront.net/software/PPL_64bit_v{{ powerpanel_version }}.deb"
        dest: /tmp/PPL.deb
        mode: "0644"
    - name: Install PowerPanel
      ansible.builtin.apt:
        deb: /tmp/PPL.deb
    - name: Cleanup Installer
      ansible.builtin.file:
        path: /tmp/PPL.deb
        state: absent
    - name: Reboot
      ansible.builtin.reboot:
    - name: Cloud Config # noqa no-changed-when
      ansible.builtin.command:
        cmd: "pwrstat -cloud -active on -account {{ secret_power_panel_user }} -password {{ secret_power_panel_pass }}"
