- name: Get Agent ID
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/endpoints?name={{ inventory_hostname }}"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: agent
  until: agent['json'] != []
  retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
  delay: 5 # Every 5 seconds

- name: Set Agent ID
  ansible.builtin.set_fact:
    agent_id: "{{ agent['json'][0]['Id'] }}"
