- name: Create LXC
  delegate_to: localhost
  block:
  - name: Create LXC
    community.general.proxmox:
      api_host: "{{ api_host }}"
      api_port: "{{ api_port }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token }}"
      ostemplate: "local:vztmpl/{{ hostvars[inventory_hostname]['lxc_template'] }}"
      hostname: "{{ ansible_hostname }}"
      node: "{{ hostvars[inventory_hostname]['pve_host'] }}"
      password: "{{ secret_pve_password }}"
      storage: "local-lvm"
      disk: "10G"
      cpus: 1
      cores: 2
      memory: 2048
      state: present
