- name: Create Sync Directory
  ansible.builtin.file:
    path: /container-vols/adguard-sync/config
    mode: "0770"
    state: directory

- name: Copy Sync Config
  ansible.builtin.copy:
    src: "{{ config_source }}/adguard/adguardhome-sync.yaml"
    dest: /container-vols/adguard-sync/config
    mode: "0770"
    force: false

- name: Copy Adguard Sync Docker-Compose
  ansible.builtin.copy:
    src: adguard-sync.yml
    dest: /container-vols/adguard-sync/docker-compose.yml
    mode: "0770"

- name: Deploy Adguard Sync
  community.docker.docker_compose_v2:
    project_src: /container-vols/adguard-sync/
    state: present
    project_name: adguard-sync
