- name: Create Directories
  ansible.builtin.file:
    path: "/container-vols/adguard/{{ item}}"
    state: directory
    mode: "0770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - config

- name: Copy DNS Cert from pfsense
  ansible.builtin.command:
    cmd: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ secret_resolver_router }}:/cf/conf/acme/dns.{{ secret_base_domain }}.* /container-vols/certs" # noqa yaml[line-length]
    creates: /container-vols/certs/dns.{{ secret_base_domain }}.fullchain

- name: Copy Config
  ansible.builtin.copy:
    src: "{{ config_source }}/adguard/AdGuardHome.yaml"
    dest: /container-vols/adguard/config/AdGuardHome.yaml
    mode: "0770"
    force: false

- name: Copy Adguard Docker-Compose
  ansible.builtin.copy:
    src: adguard.yml
    dest: /container-vols/adguard/docker-compose.yml
    mode: "0770"

- name: Deploy Adguard
  community.docker.docker_compose_v2:
    project_src: /container-vols/adguard/
    state: present
    project_name: adguard
