- name: Update GitHub Creds
  when: gh_creds_id != []
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/users/1/gitcredentials/{{ gh_creds_id[0] }}"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    body_format: json
    body:
      name: "gh-{{ secret_gh_user }}"
      username: "{{ secret_gh_user }}"
      password: "{{ secret_gh_token }}"
    method: "PUT"

- name: Create GitHub Creds
  when: gh_creds_id == []
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/users/1/gitcredentials"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    body_format: json
    body:
      name: "gh-{{ secret_gh_user }}"
      username: "{{ secret_gh_user }}"
      password: "{{ secret_gh_token }}"
    method: "POST"
    status_code:
      - 201
