- name: "Create Edge Group {{ item }}"
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/edge_groups"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    body_format: json
    body:
      name: "{{ item }}"
    method: "POST"
  register: eg_create
  failed_when:
    - eg_create.status != 200
    - (eg_create.status == 400) and (eg_create.json['message'] != 'Edge group name must be unique')
