- name: Set eg_exists
  ansible.builtin.set_fact:
    eg_exists: false

- name: Get Existing Edge Groups
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/edge_groups"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: eg_existing_groups

- name: Check for Edge Group
  ansible.builtin.set_fact:
    eg_id: "{{ eg_existing_groups.json | json_query(query) }}"
  vars:
    query: "[?Name=='{{ group }}'].Id"

- name: "Create Edge Group {{ group }}"
  when: eg_id == []
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/edge_groups"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    body_format: json
    body:
      name: "{{ group }}"
    method: "POST"
