- name: Get Existing Registry Creds
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/registries"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: dh_creds_existing

- name: Get Existing Git Creds
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/users/1/gitcredentials"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: gh_creds_existing

- name: Get Existing Edge Stacks
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/edge_stacks"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: edge_stacks_existing

- name: Get Existing Edge Groups
  ansible.builtin.uri:
    url: "https://portainer.{{ secret_base_domain }}/api/edge_groups"
    headers:
      Authorization: "Bearer {{ portainer_auth_token['json']['jwt'] }}"
    method: "GET"
  register: edge_groups_existing

- name: Check for DockerHub Creds
  ansible.builtin.set_fact:
    dh_creds_id: "{{ dh_creds_existing.json | json_query(query) }}"
  vars:
    query: "[?Name=='dockerhub'].Id | [0]"

- name: Check for GitHub Creds
  ansible.builtin.set_fact:
    gh_creds_id: "{{ gh_creds_existing.json | json_query(query) }}"
  vars:
    query: "[?name=='gh-{{ secret_gh_user }}'].id | [0]"
