---
- name: Deploy Adguard LXCs
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/repos/secrets/secrets.yml
  environment:
    PM_USER: "{{ secret_pve_username }}@pam"
    PM_PASS: "{{ secret_pve_password }}"
    AWS_ACCESS_KEY_ID: "{{ secret_tf_s3_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secret_tf_s3_secret }}"
    AWS_ENDPOINT_URL_S3: "{{ secret_tf_s3_endpoint }}"
    TF_VAR_lxc_nameserver: "{{ secret_resolver_router }}"
  roles:
    - adguard-lxc

- name: Install Adguard
  hosts: adguard
  gather_facts: false
  vars_files:
    - ~/repos/secrets/secrets.yml
  pre_tasks:
    - name: Wait for LXCs to start
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 600
  roles:
    - ssh-keys
    - dns-cert
    - adguard

- name: Update Adguard LXCs DNS resolver
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/repos/secrets/secrets.yml
  environment:
    PM_USER: "{{ secret_pve_username }}@pam"
    PM_PASS: "{{ secret_pve_password }}"
    AWS_ACCESS_KEY_ID: "{{ secret_tf_s3_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secret_tf_s3_secret }}"
    AWS_ENDPOINT_URL_S3: "{{ secret_tf_s3_endpoint }}"
    TF_VAR_lxc_nameserver: "{{ secret_resolver_adguard }}"
  roles:
    - adguard-lxc

- name: Install Adguard Sync
  hosts: adguard_sync
  gather_facts: false
  vars_files:
    - ~/repos/secrets/secrets.yml
  vars:
    golang_version: 1.23.1
  pre_tasks:
    - name: Wait for LXCs to start
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 600
  roles:
    - ssh-keys
    - dns-cert
    - adguard-sync
