- name: Portainer Admin Install
  hosts: portainer_admin
  vars_files:
    - ~/repos/secrets/secrets.yml
    - ~/repos/secrets/portainer.yml
  gather_facts: false
  roles:
    - portainer-admin

- name: Portainer Edge Agent Install
  hosts: portainer_agents
  gather_facts: true
  vars_files:
    - ~/repos/secrets/secrets.yml
    - ~/repos/secrets/portainer.yml
  roles:
    - portainer-agent

- name: Portainer Edge Groups and Stacks
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/repos/secrets/secrets.yml
    - ~/repos/secrets/portainer.yml
  roles:
    - portainer-groups-stacks
