---
- name: Security Setup
  hosts: servers
  gather_facts: false
  vars:
    ansible_user: "{{ local_user }}"
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - security

- name: Basic Setup
  hosts: servers
  gather_facts: false
  vars:
    powerpanel_version: 1.4.1
  roles:
    - pre-reqs
    - secondary-storage
    - patch
    - tailscale
    - starship
    - powerpanel

- name: Docker Setup
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - docker
