- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "https://github.com/{{ secret_gh_user }}.keys"

- name: Copy Private Key
  ansible.builtin.copy:
    src: "/home/{{ ansible_user }}/repos/secrets/id_{{ inventory_hostname }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519"
    mode: "0600"

- name: Set Passwordless Sudo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
    create: true
    mode: "0644"

- name: Set SSH to Key Only
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: "#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: 'Restart SSHD'

- name: Ensure Debian Repos Exist
  become: true
  ansible.builtin.deb822_repository:
    name: debian
    types: deb
    uris:
      - http://deb.debian.org/debian
    suites:
      - bookworm
      - bookworm-updates
    components:
      - main
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Ensure Debian Security Repos Exist
  become: true
  ansible.builtin.deb822_repository:
    name: debian-security
    types: deb
    uris:
      - http://deb.debian.org/debian-security
    suites:
      - bookworm-security
    components:
      - main
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Remove Debian DVD Repo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: .*cdrom.*
    state: absent

- name: Install Package Prereqs
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - python3-full
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - jq
    update_cache: true

- name: Configure Git User
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ secret_git_username }}"
- name: Configure Git User
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ secret_email }}"

- name: Create 'default' venv folder
  ansible.builtin.file:
    path: ~/venvs/default
    state: directory
    mode: "0770"

- name: Install Python Prereqs
  ansible.builtin.pip:
    name:
      - github3.py
      - PyYAML
      - jmespath
    virtualenv: ~/venvs/default
    virtualenv_site_packages: true
